def get_class_interpretation(class_name: str) -> str:
    """Returns a cautious interpretation based ONLY on the acoustic class."""
    interpretations = {
        "Normal": "The model classified the analyzed respiratory sound as Normal. This does not rule out a medical condition and should not be interpreted as a medical diagnosis.",
        "Crackle": "The model detected an acoustic pattern classified as Crackle. This finding alone does not establish a disease diagnosis. Persistent or concerning symptoms should be evaluated by a qualified healthcare professional.",
        "Wheeze": "The model detected an acoustic pattern classified as Wheeze. This is an acoustic classification result and does not determine the underlying medical cause.",
        "Crackle + Wheeze": "The model detected acoustic patterns classified as both Crackle and Wheeze. This result does not establish a medical diagnosis and should be discussed with a qualified healthcare professional when clinically appropriate."
    }
    return interpretations.get(class_name, "Classification result is not recognized. This is not a medical diagnosis.")


def get_general_wellness_guidance() -> list[dict[str, str]]:
    """Returns general non-prescriptive wellness guidance."""
    return [
        {
            "category": "Sleep",
            "guidance": "Aim for a consistent sleep schedule and adequate rest."
        },
        {
            "category": "Hydration",
            "guidance": "Maintain adequate fluid intake according to individual needs."
        },
        {
            "category": "Physical Activity",
            "guidance": "Maintain appropriate regular physical activity if medically suitable."
        },
        {
            "category": "Environment",
            "guidance": "Reduce exposure to smoke, dust, and known respiratory irritants."
        },
        {
            "category": "Air Quality",
            "guidance": "Avoid prolonged exposure to heavily polluted environments when possible."
        },
        {
            "category": "Nutrition",
            "guidance": "Maintain a balanced diet rich in essential nutrients."
        },
        {
            "category": "Stress Management",
            "guidance": "Use appropriate stress-management practices."
        }
    ]


def get_daily_routine() -> dict[str, list[str]]:
    """Returns a generic healthy routine."""
    return {
        "Morning": [
            "Wake up consistently at a regular time",
            "Hydrate with a glass of water",
            "Light movement or stretching",
            "Consume a balanced breakfast"
        ],
        "Day": [
            "Incorporate regular movement into your schedule",
            "Maintain adequate hydration throughout the day",
            "Consume balanced meals",
            "Avoid smoking and known respiratory irritants"
        ],
        "Evening": [
            "Engage in light, relaxing activity",
            "Practice relaxation techniques",
            "Reduce excessive screen exposure before sleep"
        ],
        "Night": [
            "Maintain a consistent sleep schedule",
            "Ensure adequate sleep duration in a comfortable environment"
        ]
    }


def get_professional_guidance() -> str:
    """Returns cautious guidance on seeking professional help."""
    return "Consider consulting a qualified healthcare professional if respiratory symptoms persist, worsen, or interfere with normal activities."


def get_disclaimer() -> str:
    """Returns the mandatory AI disclaimer."""
    return "This report is generated by an AI-assisted respiratory sound classification system. It is not a medical diagnosis, medical prescription, or substitute for evaluation by a qualified healthcare professional."
